
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    CODECOV_TOKEN: 'cee0e505-c12e-4139-aa43-621fb16a2347'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
      condition: eq(variables['PACKAGER'], 'conda')
    - script: |
        continuous_integration\\install.cmd
      displayName: 'Install'
    - script: |
        continuous_integration\\test_script.cmd
      displayName: 'Test threadpoolctl'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(JUNITXML)'
        testRunTitle: ${{ format('{0}-$(Agent.JobName)', parameters.name) }}
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
    - script: |
        bash continuous_integration\\upload_codecov.sh
      displayName: 'Upload to codecov'
      condition: succeeded()
